apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: biomining-web
  labels:
    app: biomining-web
    version: 1-0-0
    environment: production
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        app: biomining-web
        version: 1-0-0
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 50
      timeoutSeconds: 600
      containers:
      - image: gcr.io/PROJECT_ID/biomining-web
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: BIOMINING_ENVIRONMENT
          value: "production"
        - name: PYTHONPATH
          value: "/app"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/status
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/status
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
  traffic:
  - percent: 100
    latestRevision: true